---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
data:
  PORT: "{{- with .Values.settings.port }}{{ . }}{{- else }}8080{{- end }}"
  METRICS_PORT: "{{- with .Values.settings.metricsPort }}{{ . }}{{- else }}8081{{- end }}"
  DEBUG: "{{- with .Values.settings.debug }}{{ . }}{{- else }}false{{- end }}"
  BACKEND_URL: "{{- with .Values.settings.backendUrl }}{{ . }}{{- else }}http://localhost:8080{{- end }}"
---