name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '>=1.21.0'

      - name: Build and test Go code
        run: |
          go build ./...
          go test ./...

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: supporttools/powerdns-admin-proxy
          tags: ${{ github.sha }}, ${{ github.run_number }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
    
      - name: Lint Helm Chart
        run: helm lint ./charts/powerdns-admin-proxy/
    
      - name: Package Helm Chart
        run: helm package ./charts/powerdns-admin-proxy/ -d ./charts --app-version ${{ github.run_number }}
    
      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: SupportTools/helm-chart
          path: ./helm-chart-repo
    
      - name: Add Helm Chart
        run: cp ./charts/*.tgz ./helm-chart-repo/
    
      - name: Update Helm Repo Index
        run: cd ./helm-chart-repo && helm repo index ./
    
      - name: Commit and Push
        run: |
          cd ./helm-chart-repo
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Add new chart version"
          git push
